services:
  web:
    build: .
    container_name: flask-app
    # command: ls
    # command: flask run --host=0.0.0.0 --port=8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://todo_user:1234@db:5432/transactions-app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: transactions-app
    volumes:
      - postgres-data:/var/lib/postgresql/data



volumes:
  postgres-data: